### ISSUE TITLE
Teaser-list auto-populate from /products/

### ISSUE THREAD

**Issue by venturewise** [hlxsites/merative#183]
When the teaser-list is authored with a single link to /products, content does not seem to auto-populate:
![image](https://user-images.githubusercontent.com/3883795/231165944-beec09c4-e29c-4c95-a90b-1a5c6ed1d312.png)

However, if I then add the manual information after this solitary link, it does auto-populate:
![image](https://user-images.githubusercontent.com/3883795/231166459-44d85d71-0446-4efa-9b36-7b47808b5e80.png)
as seen here https://main--merative2--hlxsites.hlx.page/employers

Word doc author page:
https://merative.sharepoint.com/:w:/r/sites/Merative.comWebsite/_layouts/15/Doc.aspx?sourcedoc=%7BB7C0517A-648C-4A71-83A1-5DCED3A0B822%7D&file=employers.docx&action=default&mobileredirect=true

**Comment by amol-anand** [comment]
you need to publish the target page for it to be indexed into helix-query.json which is what powers the automation.

**Comment by amol-anand** [comment]
I published the target page, it got indexed in the query-index.json which is what is powering the automation. Removed the manually curated link added in the block since it was a duplicate. 

If you want to change the description / title that shows up here, it can be updated in the metadata of the target page and published for the index to be updated.

**Comment by helms-charity** [comment]
Thanks for the explanation, looks fixed.
