### ISSUE TITLE
Adobe Sidekick not loading on Chrome

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#184]
Team, some of our content authors have not been able to get the sidekick extension to load sometimes. Any reasons why that may be? 

https://user-images.githubusercontent.com/111377779/231202554-6dcd2793-3219-4547-9547-fa7980f13c31.mp4

**Comment by arumsey** [comment]
@keith-kaplan I have not seen that issue yet. There could possibly be a script that is failing when the Sidekick attempts to load. It looks like you are using Chrome and MacOS in the video. Can you confirm the issue is still occurring? Also, do you know what GitHub URL their sidekick is pointing to? All the new functionality is still in the `merative2` repo so existing authors would probably still be referencing the `merative` repo on their Sidekick.

**Comment by helms-charity** [comment]
@keith-kaplan how is this working for your team lately?

**Comment by keith-kaplan** [comment]
I think it was a one time for Caroline. I have not encountered this; we can close this out, to be honest.
