### ISSUE TITLE
Add ability to have an og:image on every page

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#246]
I don't think this feature is available, but can we create the ability for an author to have an og:image. If an author chooses not to have an og:image (e.g. they forget or think it's not essential), can we default the og:image to a generic Merative image (which, I can provide).

**Comment by helms-charity** [comment]
@keith-kaplan , I believe the current logic works where if "Image" is not defined in the metadata section, then the 1st image on the page will be used for og:image in the page head. And if there are no images at all on the page (such as the blog home page), then this image is served (but is not found right now) https://www.merative.com/default-meta-image.png?width=1200&#x26;format=pjpg&#x26;optimize=medium.

However, when you inspect the page in the browser console for https://main--merative2--hlxsites.hlx.page pages, the URL for those og:images is **https://www.merative.com/**, so the image currently is a 404 for pages other than blog articles.

Examples:
- See https://main--merative2--hlxsites.hlx.page/health-plans for an example where no image is defined... it uses the leadspace image because there's no image in the Word doc under Metadata (seen if you copy the path in the browser console /media_147a0636da62c11bd1b8452a144890c111235a98a.png?width=1200&format=pjpg&optimize=medium and pasting after the hlx.page URL).
- In this page https://main--merative2--hlxsites.hlx.page/life-sciences it is showing the microscope image that I defined in the Metadata https://main--merative2--hlxsites.hlx.page/media_168c18822e7e0fe0c631f005556897e608e3cb21c.jpeg?width=2000&format=webply&optimize=medium .
- In the case where there is NO image at all (such as the blog home page), there is a default image which currently is a 404, so I think we just need to publish one with that name.  
- However, I also see that the URL of this default image has a mangled address, so I will look into dhis. `https://www.merative.com/default-meta-image.png?width=1200&#x26;format=pjpg&#x26;optimize=medium`

**Comment by amol-anand** [comment]
The reason the url is www.merative.com is because that is what we have in the helix config as the CDN endpoint. That should work normally if we have a default image published.

**Comment by helms-charity** [comment]
@keith-kaplan I tested out placing a PNG file at the root of your sharepoint, then previewing it -- This URL works well. Just replace my PNG with your desired one and re-preview it.

https://main--merative2--hlxsites.hlx.page/default-meta-image.png?width=1200&#x26;format=pjpg&#x26;optimize=medium

This will only work for merative2 and not the existing site, until we go live with Phase 2.

**Comment by keith-kaplan** [comment]
This is great. Thank you for the explanation.

If we wanted to overwrite the og:image manually with metadata table. Would the value be og:image in the table and then just put the image you want to use in the table?

**Comment by helms-charity** [comment]
@keith-kaplan it's easier than that -- just upload the desired image as "Image", like this:
![image](https://user-images.githubusercontent.com/3883795/236885326-0d07200a-6434-4ff2-861c-eb0ae8364163.png)

**Comment by keith-kaplan** [comment]
Always a delightful surprise when things are this easy. Thank you.

**Comment by arumsey** [comment]
The default image has been moved from the root to `/images/meta/default-meta-image.png` to keep it out of the root folder.

**Comment by helms-charity** [comment]
Closing. In the end, we decided to keep the "default-meta-image.png" out of the sites root, and instead the image can be replaced whenever needed in the /images director. We've set it up so that /default-meta-image.png will redirect to /images/meta/default-meta-image.png.
