### ISSUE TITLE
Solution List/Teaser List Block does not need grey line at end of cards

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#255]
We do not need to add a grey line at the bottom of the teaser list block. Only in between cards.

https://main--merative2--hlxsites.hlx.page/
https://main--merative2--hlxsites.hlx.page/company

<img width="1361" alt="image" src="https://github.com/hlxsites/merative/assets/111377779/54f5628c-0955-4eb8-8fef-bfcaef7bf18d">

**Comment by helms-charity** [comment]
@keith-kaplan What is there is not an even number of items? Say "Real-world evedence" was not there. Would the one above it still have a grey line? And would Social Program Management, next to it?

**Comment by helms-charity** [comment]
Right now, all of them have their own grey lines. When next to each other, the lines butt up against each other, creating a visual that the line spans both columns. So a lot of rework on that would need to be done.

**Comment by keith-kaplan** [comment]
I see what you mean. This might be a good comment to respond to for Putra and Saad.

**Comment by arumsey** [comment]
Is resolving this a Phase 2 blocker?

**Comment by arumsey** [comment]
This can be resolved using some creative CSS since we know there are only 2 possible columns.

```
  .teaser-card:nth-child(2n + 1):nth-last-child(-n + 2),
  .teaser-card:nth-child(2n + 1):nth-child(2n + 1):nth-last-child(-n + 2) ~ .teaser-card {
    border-bottom: none;
  }
```

**Odd number of items**
<img width="682" alt="image" src="https://github.com/hlxsites/merative/assets/1004204/d25fed4c-ed27-4127-ada5-13afdbae7a8c">

**Even number of items**
<img width="709" alt="image" src="https://github.com/hlxsites/merative/assets/1004204/ea38f277-13af-4de9-a2ca-fa067b013078">
