### ISSUE TITLE
Ana's design QA review

### ISSUE THREAD

**Issue by anabarcelona** [hlxsites/merative#65]
Hi @amol-anand please find my review of the blog homepage below. There maybe some overlap with Sachin's feedback but wanted to give it a review as well.

Dev site is on the left, design is on the right

**Homepage 1440:**
<img width="2329" alt="image" src="https://user-images.githubusercontent.com/47047225/208129442-c8c728cd-f080-4e2e-a231-9e3ae2721746.png">

1. Merative logo is being stretched between breakpoints. Also, please include as SVG.(**Pending** - Amol)
2. Please check the font for the Merative Blog title. The weight we are using is light. &check;
3. Opening paragraph under title looks smaller &check;
4. Please check the font specs on the featured story, type looks smaller on dev &check;
5. Height of featured card should be fixed and taller per the design &check;
6. Let's not include the person's title in the by-line (**Pending** - Needs review as this is coming from page metadata of blog article)
7. Cards are missing their corner radius &check;
8. Featured card image inside corner radius needs to be removed. &check;
9. Card hover states need to match figma design &check;
10. Reduce space below titles in side bar under Categories, Audience and Topic. Please reference Figma for correct spacing &check;
11. Arrow style for side bar needs to match Figma. Please add those as SVG's &check; _(AA: they were SVGs but went with the SVG that was in the figma vs the icon library that we used initially)_
12. All blacks needs to be set in our Carbon color. &check;

**Category Page 1440**

<img width="2265" alt="image" src="https://user-images.githubusercontent.com/47047225/208131056-2a0809a7-aecb-4646-a398-03adac8fedf2.png">

1. Background color needs to be white &check;

**Article Page 1440**

https://main--merative--hlxsites.hlx.page/blog/connecting-with-the-clinical-development-community

<img width="2340" alt="image" src="https://user-images.githubusercontent.com/47047225/208131648-2353e8d8-0025-4d18-9925-d7375ce6f389.png">

1. Spacing below breadcrumbs needs to match figma &check;
2. sidebar title "in this article" and Share via not styled correctly &check;
3. Please match share icons - looks like they are colored. They should be white &check;
4. Article image size needs to match figma. Looks too big (Please look at comment below) 
5. Only include person's name in the byline. No titles (This needs to be fixed in the content - is there any place you will need to use the titles in the future?)
6. Body size needs to match figma. Looks too small &check;
7. Related articles missing background color &check;
8. In page links need to be styled correctly. &check; (please see comment below)
9. Lead gen banner, reduce space below title and increase body font size to match Figma design. &check;
10. I've updated our Type specs... please follow those here: https://www.figma.com/file/7tYrUju8fdnQFsx3oXAqRC/Blog--Project-Franklin?node-id=1056%3A3127&t=pL5BLx5LaSFnVBad-1

**Comment by amol-anand** [comment]
@anabarcelona 
> 9. Card hover states need to match figma design 

> Figma note -> Card hover states: image enlarges slightly, card dropshadow and title underlines and turns purple. 

This is what is happening on the site now. What is different in the Figma file that is not happening on the site? Any details are much appreciated!

**Comment by amol-anand** [comment]
@anabarcelona 

> 10. Reduce space below titles in side bar under Categories, Audience and Topic. Please reference Figma for correct spacing
This is 24px in the figma file. Same in the site. Am I missing something else here?

**Comment by amol-anand** [comment]
> Article image size needs to match figma. Looks too big

We don't usually put heights on images in content since you want the flexibility for authors to add any images they want. The width of the container will dictate the image size. It will take the full width and adjust accordingly based on the image. Also automatically using the right rendition based on browser width which is good for performance.

In the screenshot above you are looking at two different pages which have different images altogether. If you looked at the same page in both systems, the difference is minimal. 

/blog/connecting-with-the-clinical-development-community
on merative.com production: 864 X 574 pixels
on Franklin: 840 X 558 pixels

I would recommend against comparing real content / imagery to what is in a design file since the design only has the content that is ideal. Comparing design elements - sure; comparing content - not going to be the same. In the real world of a fully functioning website and a CMS, we need flexibility for marketing to do what they need to do and not curtail their authoring experience. They system should work no matter what types of content / imagery they want to put in. Hope that makes sense.  

I would recommend not changing anything w.r.t image height in articles specifically unless we had a really good reason for it. I would let the width dictate it automatically.

**Comment by amol-anand** [comment]
> 8. In page links need to be styled correctly. 

I put in the logic to center all links in a p tag- but that might have unintended consequences like the source links at the bottom of the article will also get centered. Want to make it easy for authors so don't want them to have to do anything special for this and we have automated this for them for now. Let's discuss more if it doesn't work for whatever reason)
