### ISSUE TITLE
Add Digital Data Layer Metadata properties to webpages

### ISSUE THREAD

**Issue by keith-kaplan** [hlxsites/merative#86]
On our AEM site we have a handful of metadata properties in our Digital Data Layer. This feeds our web analytics. We'd like to bring these properties into any page that gets published in Franklin. Here is an example of what it looks like the DOM. We're having some issues with this in AEM as you can see with some of the formattings....

<img width="859" alt="image" src="https://user-images.githubusercontent.com/111377779/209152120-4d3cdd47-3a5f-4013-888b-a8f03ff0fe87.png">

**Comment by amol-anand** [comment]
@keith-kaplan some of this can be configured directly from Launch. It can look at the page meta and then pull in all the info it needs. Anything you need to add to the meta of the html can be added using Page Metadata table at the end of the page's word document. That would be the simplest way instead of complicating it with a digitalData object etc.. Thoughts? We can sync up after the break to see what would be the most straightforward way to get this data into the data layer.

**Comment by keith-kaplan** [comment]
Sounds good, I definitely want to make this a top item for phase 2 as this info directly influences our analytics reporting.

**Comment by keith-kaplan** [comment]
@amol-anand  putting some items we'll want to capture in the metadata fields during the authoring process.

1. Organization Function
2. Page Category
3. Parent
4. Product Family
5. Page Title (I think this is already set in the word document, we just need to figure out how we can get this to be brought into AA)

Let me know if you'd like to discuss when we begin work.

**Comment by amol-anand** [comment]
Two ways to do this - one is to add this info at the page level to metadata block at the end of the page OR we can update it for each url in the metadata.xlsx in one shot for bulk edits. Will the author know/care about any of these? Or is this more of a content manager who would know about this info and can edit in one place which is the metadata.xlsx? For example, page title, description and stuff would be something that the author would enter in the page, but page category/product family/org function, not sure if they would know that or not.

**Comment by keith-kaplan** [comment]
Good point. I'd like to have it in the metadata boxes in each page. Ideally, things like page category and org function would not change much. The thing that will change is the Parent/Product Family info.

**Comment by amol-anand** [comment]
Ok great. so that makes it easy. You can go ahead and add the items to the Page metadata and it will automatically show up in the HTML meta tags. Once that happens we can then map to any of the analytics variables in Launch directly. Having them appear before we make changes to Launch would be beneficial so we can test and make sure all of them are making its way to analytics.

**Comment by keith-kaplan** [comment]
@amol-anand  we can probably mark this as done.
